### ISSUE TITLE
node 

### ISSUE THREAD

**Issue by arkarkyaw88** [sbis04/flutter_stream#4]
Hello 
When i clone and run node main.js 

ak@ak-Inspiron-5447:~/flutteradmin/flutter_stream$ node main.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/home/ak/flutteradmin/flutter_stream/main.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
ak@ak-Inspiron-5447:~/flutteradmin/flutter_stream$ node -v
v12.22.5
ak@ak-Inspiron-5447:~/flutteradmin/flutter_stream$ npm install
npm WARN saveError ENOENT: no such file or directory, open '/home/ak/flutteradmin/flutter_stream/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/ak/flutteradmin/flutter_stream/package.json'
npm WARN flutter_stream No description
npm WARN flutter_stream No repository field.
npm WARN flutter_stream No README data
npm WARN flutter_stream No license field.

up to date in 1.923s
found 0 vulnerabilities

   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New major version of npm available! 6.14.14 → 7.21.1      │
   │   Changelog: https://github.com/npm/cli/releases/tag/v7.21.1   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

ak@ak-Inspiron-5447:~/flutteradmin/flutter_stream$ node main.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/home/ak/flutteradmin/flutter_stream/main.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by arkarkyaw88** [comment]
thanks.. its fine now. when im installed nmp install cmd.
